import Link from "next/link"
import type { Metadata } from "next"

export const metadata: Metadata = {
  title: "Terms of Service — ScoutCurate",
  description: "Terms of Service for the ScoutCurate AI Gift Finder Chrome Extension.",
}

const LAST_UPDATED = "March 27, 2026"

export default function TermsPage() {
  return (
    <div className="max-w-3xl mx-auto px-4 sm:px-6 py-16">
      <div className="mb-10">
        <Link href="/" className="text-sm text-scout-primary hover:underline">← Back to ScoutCurate</Link>
        <h1 className="text-3xl sm:text-4xl font-black text-gray-900 mt-4 mb-2">Terms of Service</h1>
        <p className="text-sm text-gray-400">Last updated: {LAST_UPDATED}</p>
      </div>

      <div className="prose prose-gray max-w-none space-y-8 text-gray-700 text-[15px] leading-relaxed">

        <section>
          <p>
            Welcome to <strong>ScoutCurate</strong> ("we," "our," or "us"), accessible at{" "}
            <a href="https://scoutcurate.com" className="text-scout-primary hover:underline">scoutcurate.com</a> and
            through our Chrome browser extension. By using ScoutCurate, you agree to these Terms of Service. If you
            do not agree, please do not use our extension or website.
          </p>
        </section>

        <Section title="1. Description of Service">
          <p>
            ScoutCurate is a free Chrome browser extension that uses artificial intelligence (via the OpenAI API)
            to generate gift recommendations based on voice or text input provided by the user. Results are
            displayed as product search links on Amazon.com.
          </p>
          <p className="mt-3">
            ScoutCurate operates two modes:
          </p>
          <ul className="list-disc list-inside space-y-1 mt-2">
            <li><strong>Scout</strong> — generates age-appropriate gift ideas for children, intended for use by parents, guardians, and adults shopping on behalf of a child.</li>
            <li><strong>Curate</strong> — generates gift ideas for adults, focused on lifestyle, luxury, and personal taste.</li>
          </ul>
        </Section>

        <Section title="2. Eligibility and Age Requirements">
          <p>
            You must be at least <strong>13 years of age</strong> to use ScoutCurate. By using this service,
            you represent that you meet this requirement.
          </p>
          <p className="mt-3">
            ScoutCurate's <strong>Scout mode is not directed at children under 13</strong>. It is a tool for
            adults (parents, guardians, gift-givers) to find gift ideas <em>for</em> children. If you are under
            13, please have a parent or guardian use this extension on your behalf.
          </p>
        </Section>

        <Section title="3. AI-Generated Recommendations Disclaimer">
          <p>
            <strong>All gift recommendations provided by ScoutCurate are generated by artificial intelligence</strong> and
            are for informational and entertainment purposes only. We make no representations or warranties
            regarding the accuracy, completeness, safety, quality, price, or availability of any recommended product.
          </p>
          <p className="mt-3">
            You are solely responsible for evaluating the suitability of any product before purchase. ScoutCurate
            does not endorse, inspect, or verify any recommended product. Always use your own judgment when
            purchasing items, especially for children.
          </p>
        </Section>

        <Section title="4. Affiliate Relationship">
          <p>
            You acknowledge that clicking "Buy on Amazon" buttons may result in ScoutCurate earning a commission through the Amazon Services LLC Associates Program. <strong>This does not increase the price you pay.</strong>
          </p>
          <p className="mt-3">
            Amazon and the Amazon logo are trademarks of Amazon.com, Inc. or its affiliates.
          </p>
        </Section>

        <Section title="5. User Responsibility">
          <p>
            Users are responsible for verifying the safety, price, and suitability of any product on Amazon before purchasing.
          </p>
          <p className="mt-3">
            For <strong>Scout mode (Kids)</strong>, parents and guardians must exercise final judgment on toy safety and age ratings. AI-generated recommendations are a starting point, not a substitute for parental review.
          </p>
          <p className="mt-3">
            While we strive for accuracy, AI can occasionally suggest items that are out of stock, incorrectly priced, or age-inappropriate. Always verify on Amazon before purchasing.
          </p>
        </Section>

        <Section title="6. User Conduct">
          <p>You agree not to use ScoutCurate to:</p>
          <ul className="list-disc list-inside space-y-1 mt-2">
            <li>Generate recommendations for illegal, dangerous, or harmful products</li>
            <li>Attempt to circumvent, reverse engineer, or interfere with the extension</li>
            <li>Use the service in any way that violates applicable laws or regulations</li>
            <li>Violate OpenAI's usage policies through your prompts or inputs</li>
          </ul>
        </Section>

        <Section title="7. Intellectual Property">
          <p>
            The ScoutCurate name, logo, website design, and extension code are owned by ScoutCurate and protected
            by applicable intellectual property laws. You may not copy, modify, or distribute our materials
            without prior written permission.
          </p>
          <p className="mt-3">
            AI-generated gift recommendations are not owned by ScoutCurate. They are generated dynamically
            based on your input and are subject to OpenAI's terms.
          </p>
        </Section>

        <Section title="8. Limitation of Liability">
          <p>
            To the fullest extent permitted by law, ScoutCurate, its owners, operators, and affiliates shall not
            be liable for any indirect, incidental, special, consequential, or punitive damages arising from your
            use of the service, including but not limited to:
          </p>
          <ul className="list-disc list-inside space-y-1 mt-2">
            <li>Purchase decisions made based on AI-generated recommendations</li>
            <li>Product quality, safety, or availability issues</li>
            <li>OpenAI API charges or outages</li>
            <li>Any errors or inaccuracies in recommendations</li>
          </ul>
          <p className="mt-3">
            ScoutCurate is provided "as is" and "as available" without warranties of any kind.
          </p>
        </Section>

        <Section title="9. Third-Party Services">
          <p>
            ScoutCurate integrates with third-party services including <strong>OpenAI</strong> and{" "}
            <strong>Amazon</strong>. Your use of these services is governed by their respective terms of service
            and privacy policies. ScoutCurate is not responsible for the practices or content of any third-party
            service.
          </p>
        </Section>

        <Section title="10. Changes to These Terms">
          <p>
            We may update these Terms of Service from time to time. Changes will be posted on this page with an
            updated "Last updated" date. Continued use of ScoutCurate after changes constitutes acceptance of the
            revised terms.
          </p>
        </Section>

        <Section title="11. Governing Law">
          <p>
            These Terms are governed by the laws of the United States. Any disputes arising from these Terms or
            your use of ScoutCurate shall be resolved through binding arbitration or in the courts of competent
            jurisdiction.
          </p>
        </Section>

        <Section title="12. Contact">
          <p>
            Questions about these Terms? Contact us at:{" "}
            <a href="mailto:hello@scoutcurate.com" className="text-scout-primary hover:underline">hello@scoutcurate.com</a>
          </p>
        </Section>

      </div>
    </div>
  )
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section>
      <h2 className="text-lg font-bold text-gray-900 mb-3 border-b border-gray-100 pb-2">{title}</h2>
      {children}
    </section>
  )
}
