import Link from "next/link"

export function Footer() {
  const year = new Date().getFullYear()

  return (
    <footer className="bg-gray-950 text-gray-400 pt-12 pb-8">
      <div className="max-w-6xl mx-auto px-4 sm:px-6">
        {/* Affiliate + AI Disclosure — required by Amazon Associates & FTC */}
        <div className="border border-gray-700 rounded-xl p-4 mb-10 bg-gray-900">
          <p className="text-xs leading-relaxed text-gray-400">
            <span className="font-semibold text-gray-300">Affiliate Disclosure:</span> ScoutCurate is a participant in the Amazon Services LLC Associates Program, an affiliate advertising program designed to provide a means for sites to earn advertising fees by advertising and linking to Amazon.com. As an Amazon Associate, we earn from qualifying purchases. Prices and availability are subject to change.
          </p>
          <p className="text-xs leading-relaxed text-gray-400 mt-2">
            <span className="font-semibold text-gray-300">AI Disclosure:</span> All gift recommendations on ScoutCurate are generated by artificial intelligence (OpenAI). They are provided for informational purposes only and do not constitute professional advice. ScoutCurate does not guarantee the accuracy, safety, or suitability of any recommended product.
          </p>
        </div>

        <div className="grid grid-cols-2 sm:grid-cols-4 gap-8 mb-10">
          <div>
            <div className="flex items-center gap-2 mb-3">
              <div className="w-7 h-7 rounded-full bg-scout-primary flex items-center justify-center text-white font-black text-xs">SC</div>
              <span className="font-bold text-white text-sm">ScoutCurate</span>
            </div>
            <p className="text-xs leading-relaxed">
              AI-powered gift finder for kids and adults. Free Chrome extension.
            </p>
          </div>

          <div>
            <h4 className="font-semibold text-gray-300 text-sm mb-3">Product</h4>
            <ul className="space-y-2 text-xs">
              <li><a href="https://chrome.google.com/webstore" target="_blank" rel="noopener noreferrer" className="hover:text-white transition-colors">Chrome Extension</a></li>
              <li><Link href="/#how-it-works" className="hover:text-white transition-colors">How It Works</Link></li>
              <li><Link href="/#scout" className="hover:text-white transition-colors">Scout (Kids)</Link></li>
              <li><Link href="/#curate" className="hover:text-white transition-colors">Curate (Adults)</Link></li>
            </ul>
          </div>

          <div>
            <h4 className="font-semibold text-gray-300 text-sm mb-3">Legal</h4>
            <ul className="space-y-2 text-xs">
              <li><Link href="/terms" className="hover:text-white transition-colors">Terms of Service</Link></li>
              <li><Link href="/privacy" className="hover:text-white transition-colors">Privacy Policy</Link></li>
            </ul>
          </div>

          <div>
            <h4 className="font-semibold text-gray-300 text-sm mb-3">Contact</h4>
            <ul className="space-y-2 text-xs">
              <li><a href="mailto:hello@scoutcurate.com" className="hover:text-white transition-colors">hello@scoutcurate.com</a></li>
            </ul>
          </div>
        </div>

        <div className="border-t border-gray-800 pt-6 flex flex-col sm:flex-row items-center justify-between gap-3 text-xs">
          <p>© {year} ScoutCurate. All rights reserved.</p>
          <p className="text-center">
            Amazon and the Amazon logo are trademarks of Amazon.com, Inc. or its affiliates.
          </p>
        </div>
      </div>
    </footer>
  )
}
